Dockerfile
Justfile
deployment/create-conda-environment.sh
meson.build
wagl/f90_sources/cast_shadow_main.f90
wagl/f90_sources/cast_shadow_mask.f90
wagl/f90_sources/terrain_border_margins.f90
wagl/f90_sources/terrain_occlusion.f90
wagl/meson.build

One Fortran module defines its own `pi`, `r2d` etc variables, which conflict with ones in sys_modules.
I initially changed it to use the sys_variables itself, to be consistent with the others, but noticed that it uses slightly different types (real -> double).
To be conservative in our changes, I've instead renamed the local ones to not conflict, and kept them as reals.
(I don't know why the Fortran build recently became stricter in this. Versions of compilers etc seem the same.)
This also fixes some small things found in debugging the problem (that unfortunately didn't fix it)
- Set Fortran args globally, rather than manually. (one module wasn't using our fortran config)
- Use a separate cache for conda vs pip build. This avoids some Docker caching issues.

Fix Fortran build

---

.pre-commit-config.yaml
eugl/gqa/tasks.py
pyproject.toml
tesp/sensitivity.py
wagl/reflectance.py

Now that ruff supports black-like formatting, we can remove black.
(the newer version of black had a similar diff to some lines)

Bump pre-commit versions

---

wagl/multifile_workflow.py
wagl/singlefile_workflow.py
wagl/standardise.py

Remove parameters that propagated the land/sea raster file location needed by the now removed pixel quality code.

remove land_sea_raster leftovers from PQ removal

---

wagl/f90_sources/cast_shadow_main.f90
wagl/f90_sources/terrain_border_margins.f90

Pretty sure Fortran common blocks are broken in this environment somehow. Setting common block variables in one function and reading them from another isn't working.

Fix broken cast shadow by removing Fortran common block

---

eugl/gqa/geometric_utils.py
eugl/gqa/tasks.py

Most error messages come from the `run_command` function which captures (allegedly) the `stdout` and `stdin`. This particular invocation called the raw `check_call` function that loses the error message.
Pretty minor impact.

Better error message in GQA

---

eugl/gqa/tasks.py

Because otherwise GQA won't even consider the scene for processing

Expand GQA extent

---

wagl/standardise.py

Why?
- `card4l` does "data standardization" as one giant task but I think this breakdown is easier to understand
- it looks like a pipeline now
- let's us profile individual steps more effectively
- let's us track dependencies better
- better still would be to track which HDF5 groups are prerequisites to the tasks
- down the track maybe they can be separate `luigi` tasks, bringing back most of the advantages of `multifile_workflow` but with a level of granularity I am more comfortable with
Changes:
- not much, mostly moving code around
- I think the dependence on the NBAR/SBT bands are clearer now
- the `esun_values` were calculated as a side-effect to interpolating modtran parameters, which is probably not ideal, so refactored it to a separate function
- have separated the interpolation …

Refactor the `card4l` function into smaller pieces

---

wagl/f90_sources/compute_angles.f90
wagl/f90_sources/geod2geo.f90
wagl/f90_sources/q_cal.f90
wagl/f90_sources/satellite_angles_main.f90
wagl/f90_sources/satellite_solar_angles_main.f90
wagl/f90_sources/solar_angle.f90
wagl/f90_sources/solar_angles_main.f90
wagl/f90_sources/track_time_info.f90
wagl/meson.build
wagl/satellite_solar_angles.py

This rather large refactor still produces _identical_ results.
Why?
- so that I have to wait a _little_ less time to reproduce an issue
- time is money 💰
How?
- move time related calculations (same for all pixels) to the top-level function for solar angles
- pre-calculate orbital inclination trig functions (sin, cos, tan) and pass it to the pixel-level function
- when a trig function is repeated in an expression, pre-compute it (probably a bit overkill)
Before:
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.771    0.771  961.791  961.791 wagl/standardise.py:273(stash_oa_bands)
4  394.802   98.700  423.416  105.854 wagl/terrain_shadow_masks.py:245(calculate_cast_shadow)
2  293.811  146.905  332.816  166.408 …
```

Satellite and solar angle refactor

---

deployment/dataset-cmp
wagl/f90_sources/cast_shadow_main.f90
wagl/terrain_shadow_masks.py

This refactor does not change any outputs.
Why?
- Cast shadow calculations are not "local" (pixel-by-pixel), so they need to load surrounding pixels too
- Because of the 15m panchromatic band in Landsat imagery this means about 7GB of in memory data
- But both on AWS and NCI, the standard memory/CPU is about 4GB, which means we essentially pay twice the compute cost
- Strangely, the underlying code was carefully written to operate on smaller slices but somehow something got lost in translation
Changes:
- Emulate the outer `for` loop in the Fortran file `cast_shadow_main.f90` in our Python code
- [in Fortran `for` is called `do` because why not]
- This lets us read only a horizontal slab and pass it onto `cast_shadow_main.f90` which correctly handles it
- [so the outer `do` loop there is …

Avoid loading whole images into memory in cast shadow

---

deployment/nci/create-module.sh

The `activate` script isn't written in a way that is safe to call from within another script. It leaks arguments from the outer script — so certain arguments (in our case, the name of our module) leak through to conda's own logic.
(I have no idea why it would use the `$@` variable if it's only designed to be sourced — that's what's causing the trouble)

Fix conda activation

---

docs/source/configuration.rst
wagl/constants.py
wagl/interpolation.py

No changes in behavior. But added the capability to interpolate using the `scipy.interpolate` module.
The result is not identical but the difference in the atmospheric coefficients is <1%. It speeds up interpolation by a little (about ~10-20%).
The key finding is that we actually do not need to support/maintain the sheared bilinear interpolation method if we don't want to.

provide scipy.interpolate as an alternative

---

deployment/nci/modulefile.template
eugl/gqa/tasks.py

To fix the instability of proj data we're seeing, until that can be tracked down.
Also include a check of our assumption that an EPSG code exists.

Set a proj data folder

---

tesp/scripts/ard_pbs.py

This command was packaged as "ard_batch_summary" to avoid clashes in the unified repository, but ard_pbs jobs were still being generated with the old command. Fix it.

Fix batch_summary command

---

wagl/acquisition/__init__.py
wagl/brdf.py
wagl/dsm.py
wagl/f90_sources/cast_shadow_main.f90
wagl/margins.py
wagl/singlefile_workflow.py
wagl/slope_aspect.py
wagl/terrain_shadow_masks.py

- Fix `s2cloudless` band offset issue (offset was not being applied to B9, B10 because we don't produce ARD for them)
- Fix datasets being stuck in `interim` maturity when there is no available BRDF (ocean tiles)
- Fix Heard Island cast shadow issue (shadow calculations needs more buffer)

Fix recent issues

---

Dockerfile

but the NRT processing needs `perl` to do some argument processing.

add perl to the NRT docker image

---

README.md
deployment/environment.yaml

Resolves #55.
This PR adds some docs & troubleshooting help to ensure the right `setuptools_scm` dependency is installed, thus preventing downstream build problems.
Additional: some markdown tidying.

README docs fix for setuptools_scm 

---

.github/workflows/docker.yaml

Because of https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/, they are throwing errors.

update GitHub artifact actions

---

README.md
deployment/check-environment.sh

Closes #59.
This PR switches `deployment/check-environment.sh` to use filter objects instead of int codes. This is an attempt to prevent core dump crashes on some platforms that cannot handle int codes as the `compression=...` option.
Also added, a second check in the script to build a hdf5 dataset using default options.
I've also added a TODO to check if importing `wagl` actually initialises the filters. This was failing in some cases.

Fix hdf5 imports in `deployment/check-environment.sh`

---

deployment/nci/create-module.sh

Closes #70.
This PR covers these goals:
* Add help option to `deployment/nci/create-module.sh`
* Describe command line options for custom deployments
* Fix path handling so relative paths can be used
Result of testing these changes on `gadi`:
* Environment was created: PASS
* `check-environment` passed using the deployed module: PASS
* 350 unit tests ran, **36 failed**
There are some open questions in issue #70 which should be addressed in this review. Any comments welcome!

Add usage help to `deployment/nci/create-module.sh`

---

tests/test_geobox.py
wagl/geobox.py

This PR is a simple cleanup of `geobox.py` & `test_geobox.py` code & linting errors.
The main change is using `setUp()` & `tearDown()` methods to remove duplicated test data setup. This fixes remove ~75 lines of test code. I've left it as a `unittest` solution, instead of converting to `pytest` with fixtures (mainly to reduce the number of required external dependencies).

General cleanup of `geobox.py` & `test_geobox.py`

---

wagl/dsm.py

Replaces NaNs (absence of data, when CopDEM ocean tiles are missing because to land to report) with zeros in the DEM loading.

fix CopDEM tile NaN issue

---

deployment/configs/landsat.cfg
deployment/configs/sentinel-2.cfg
deployment/nci/luigi.cfg.template

To reflect what is working for us in production.
- We previously found reliability issues with bitshuffle, and the size difference versus lzf was not worth it.
- A default luigi task timeout stops the occasional job from running for hours with little progress.

Config template update: LZF and timeouts

---

wagl/ancillary.py
wagl/brdf.py
wagl/dsm.py

For the tiled Copernicus 30m DEM arranged in folders, we can now set the ocean mask location (`ocean_mask_path` and `extended_ocean_mask_path` for the Australian mainland and the offshore territories respectively) to the root of the DEM folder. It will then use the water-body mask layer that comes with the DEM to mask BRDF data.

Implement water body mask for tiled Copernicus DEM

---

wagl/brdf.py

Some water mask look up code was failing because of edge cases (tiny land masses).

fix unnecessary fails in only_ocean_pixels()

---

eugl/metadata.py

I'm assuming we want these represented as a zero count in the metadata, but please advise if you disagree!
```
Example datasets:
/g/data/fj7/Copernicus/Sentinel-2/MSI/L1C/2022/2022-02/15S145E-20S150E/S2A_MSIL1C_20220227T002711_N0400_R016_T55KFU_20220227T015951.zip
/g/data/fj7/Copernicus/Sentinel-2/MSI/L1C/2022/2022-03/25S145E-30S150E/S2B_MSIL1C_20220301T002049_N0400_R116_T55JGM_20220301T012734.zip
/g/data/fj7/Copernicus/Sentinel-2/MSI/L1C/2022/2022-03/30S140E-35S145E/S2A_MSIL1C_20220309T002711_N0400_R016_T55HCE_20220309T020450.zip
/g/data/fj7/Copernicus/Sentinel-2/MSI/L1C/2022/2022-04/10S130E-15S135E/S2A_MSIL1C_20220409T013711_N0400_R031_T52LHL_20220409T030537.zip
/g/data/fj7/Copernicus/Sentinel-2/MSI/L1C/2022/2022-04/10S130E-15S135E/S2B_MSIL1C_20220401T012709_N0400_R131_T53LME_20220401T02 …
```

Fix metadata gen when zero valid s2cloudless pixels

---

wagl/f90_sources/cast_shadow_main.f90
wagl/f90_sources/cast_shadow_mask.f90
wagl/f90_sources/terrain_border_margins.f90
wagl/terrain_shadow_masks.py

The new algorithm behaves better in extreme situations (such as Heard Island) where the cast shadow is very long.
We use no sun angle buffer when the DEM quality is high (Copernicus 30m DEM). It remains at 3 degrees for lower quality DEM (SRTM).

cast shadow algorithm improvements from David and Fuqin

---

tests/test_tiling.py
wagl/acquisition/base.py
wagl/reflectance.py
wagl/satellite_solar_angles.py
wagl/tiling.py

For the usual tile size used of 256, when the image width is, for example, 15361 = 60 * 256 + 1, the last tile on the first row is of size (256, 1). That is, the image fed to the Fortran routine `satellite_angle` is 1 pixel wide.
In that routine there is an assumption that the image is at least 2 pixels wide:
```fortran
!       calculate pixel size (half)
       if (j .gt. 1) then
           delxx = (alon(i, j)-alon(i, j-1))/2
       else
           delxx = (alon(i, j+1)-alon(i, j))/2
       endif
```
and so `delxx` has invalid value and the error propagates onwards.
This PR fixes it by introducing tolerance for the tiling, with an `xtol=1` for example, the last tile is allowed to have width 257, despite the tile size being 256.

Bug fix for tiling edge-case

---

tests/test_dsm.py
wagl/dsm.py
wagl/standardise.py

This PR brings the DE Antarctica DSM changes to the main ARD Pipeline branch.
The changes are:
* Modify DSM code to correctly calculate tile extents at different locations across the earth.
* Adds DSM developer tests for the tiling solution.
* Incorporates anti-meridian handling for the tiling solution.
Running the DSM module across 5 Landsat Antarctic scenes produced this `EPSG:3031` overview:

Integrate DE Ant DSM fixes into main ARD Pipeline
